# Generated by Django 4.2.1 on 2025-05-31 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'Комментарий',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('in_stock', models.BooleanField(choices=[(False, 'Нет в наличии'), (True, 'В наличии')], default=0, verbose_name='Статус')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desserts', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Десерт',
                'verbose_name_plural': 'Десерты',
            },
        ),
        migrations.CreateModel(
            name='TagDessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DessertInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField(blank=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('dessert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='catalog.dessert')),
            ],
        ),
        migrations.AddField(
            model_name='dessert',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='catalog.tagdessert', verbose_name='Теги'),
        ),
    ]
