# Generated by Django 4.2.1 on 2025-03-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
