# Generated by Django 4.2.1 on 2025-03-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_dessert_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
