# Generated by Django 4.2.1 on 2025-03-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_dessert_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='in_stock',
            field=models.BooleanField(choices=[(0, 'Нет в наличии'), (1, 'В наличии')], default=0),
        ),
    ]
