# Generated by Django 4.2.1 on 2025-04-13 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_tagdessert_dessert_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DessertInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField(blank=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('dessert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='catalog.dessert')),
            ],
        ),
    ]
