# Generated by Django 3.2.16 on 2025-05-08 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_dessertinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='dessert',
            options={'verbose_name': 'Десерт', 'verbose_name_plural': 'Десерты'},
        ),
        migrations.AddField(
            model_name='dessert',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desserts', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='in_stock',
            field=models.BooleanField(choices=[(False, 'Нет в наличии'), (True, 'В наличии')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='catalog.TagDessert', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
