# Generated by Django 4.2.1 on 2025-05-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20250508_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
